# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pol_paddles.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1226, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.optimize_around_p1 = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_around_p1.setGeometry(QtCore.QRect(100, 537, 141, 31))
        self.optimize_around_p1.setObjectName("optimize_around_p1")
        self.move_to_p1 = QtWidgets.QPushButton(self.centralwidget)
        self.move_to_p1.setGeometry(QtCore.QRect(100, 590, 93, 28))
        self.move_to_p1.setObjectName("move_to_p1")
        self.home_p1 = QtWidgets.QPushButton(self.centralwidget)
        self.home_p1.setGeometry(QtCore.QRect(100, 640, 93, 28))
        self.home_p1.setObjectName("home_p1")
        self.optimize_p1 = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_p1.setGeometry(QtCore.QRect(100, 490, 93, 28))
        self.optimize_p1.setObjectName("optimize_p1")
        self.move_to_p2 = QtWidgets.QPushButton(self.centralwidget)
        self.move_to_p2.setGeometry(QtCore.QRect(570, 580, 93, 28))
        self.move_to_p2.setObjectName("move_to_p2")
        self.optimize_around_p2 = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_around_p2.setGeometry(QtCore.QRect(570, 527, 141, 31))
        self.optimize_around_p2.setObjectName("optimize_around_p2")
        self.home_p2 = QtWidgets.QPushButton(self.centralwidget)
        self.home_p2.setGeometry(QtCore.QRect(570, 630, 93, 28))
        self.home_p2.setObjectName("home_p2")
        self.optimize_p2 = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_p2.setGeometry(QtCore.QRect(570, 480, 93, 28))
        self.optimize_p2.setObjectName("optimize_p2")
        self.optimize_p3 = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_p3.setGeometry(QtCore.QRect(990, 473, 93, 28))
        self.optimize_p3.setObjectName("optimize_p3")
        self.move_to_p3 = QtWidgets.QPushButton(self.centralwidget)
        self.move_to_p3.setGeometry(QtCore.QRect(990, 573, 93, 28))
        self.move_to_p3.setObjectName("move_to_p3")
        self.optimize_around_p3 = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_around_p3.setGeometry(QtCore.QRect(990, 520, 141, 31))
        self.optimize_around_p3.setObjectName("optimize_around_p3")
        self.home_p3 = QtWidgets.QPushButton(self.centralwidget)
        self.home_p3.setGeometry(QtCore.QRect(990, 623, 93, 28))
        self.home_p3.setObjectName("home_p3")
        self.paddle_1 = QtWidgets.QLabel(self.centralwidget)
        self.paddle_1.setGeometry(QtCore.QRect(130, 130, 55, 16))
        self.paddle_1.setObjectName("paddle_1")
        self.paddle_2 = QtWidgets.QLabel(self.centralwidget)
        self.paddle_2.setGeometry(QtCore.QRect(570, 130, 55, 16))
        self.paddle_2.setObjectName("paddle_2")
        self.paddle_3 = QtWidgets.QLabel(self.centralwidget)
        self.paddle_3.setGeometry(QtCore.QRect(1000, 120, 55, 16))
        self.paddle_3.setObjectName("paddle_3")
        self.device_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.device_1.setGeometry(QtCore.QRect(100, 10, 81, 20))
        self.device_1.setObjectName("device_1")
        self.device_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.device_2.setGeometry(QtCore.QRect(100, 40, 81, 20))
        self.device_2.setObjectName("device_2")
        self.device_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.device_3.setGeometry(QtCore.QRect(100, 70, 81, 20))
        self.device_3.setObjectName("device_3")
        self.device_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.device_4.setGeometry(QtCore.QRect(230, 10, 81, 20))
        self.device_4.setObjectName("device_4")
        self.device_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.device_5.setGeometry(QtCore.QRect(230, 40, 81, 20))
        self.device_5.setObjectName("device_5")
        self.device_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.device_6.setGeometry(QtCore.QRect(230, 70, 81, 20))
        self.device_6.setObjectName("device_6")
        self.optimize_all_p = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_all_p.setGeometry(QtCore.QRect(700, 50, 93, 28))
        self.optimize_all_p.setObjectName("optimize_all_p")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.optimize_around_p1.setText(_translate("MainWindow", "Optimize around"))
        self.move_to_p1.setText(_translate("MainWindow", "Move to"))
        self.home_p1.setText(_translate("MainWindow", "Home"))
        self.optimize_p1.setText(_translate("MainWindow", "Optimize "))
        self.move_to_p2.setText(_translate("MainWindow", "Move to"))
        self.optimize_around_p2.setText(_translate("MainWindow", "Optimize around"))
        self.home_p2.setText(_translate("MainWindow", "Home"))
        self.optimize_p2.setText(_translate("MainWindow", "Optimize "))
        self.optimize_p3.setText(_translate("MainWindow", "Optimize "))
        self.move_to_p3.setText(_translate("MainWindow", "Move to"))
        self.optimize_around_p3.setText(_translate("MainWindow", "Optimize around"))
        self.home_p3.setText(_translate("MainWindow", "Home"))
        self.paddle_1.setText(_translate("MainWindow", "Paddle 1"))
        self.paddle_2.setText(_translate("MainWindow", "Paddle 2"))
        self.paddle_3.setText(_translate("MainWindow", "Paddle 3"))
        self.device_1.setText(_translate("MainWindow", "device 1"))
        self.device_2.setText(_translate("MainWindow", "device 2"))
        self.device_3.setText(_translate("MainWindow", "device 3"))
        self.device_4.setText(_translate("MainWindow", "device 4"))
        self.device_5.setText(_translate("MainWindow", "device 5"))
        self.device_6.setText(_translate("MainWindow", "device 6"))
        self.optimize_all_p.setText(_translate("MainWindow", "Optimize_all_p"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

