# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Python Interrogate Check
        # You may pin to the exact commit or the version.
        # uses: JackMcKew/python-interrogate-check@b375952bb548087b1c30388fc6393ecff364614a
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          # File or directory to run interrogate on.
          path: 
          # Fail when coverage % is less than a given amount.
          fail-under: # optional, default is 80
          # Generate a `shields.io` status badge (an SVG image) in at a given file or directory.
          badge-location: # optional, default is .
